services:
  - type: web
    name: inv-backend
    env: docker
    plan: free # or "starter", "professional", etc.
    buildCommand: ""
    startCommand: "dotnet backend.dll" # or your backend start command
    dockerfilePath: backend/Dockerfile # Path to your backend Dockerfile
    dockerBuildContext: ./ # Context is the root directory
    port: 8080
    regions:
      - oregon # Choose the appropriate region

  # - type: web
  #   name: inv-frontend
  #   env: docker
  #   plan: free # or other plans as needed
  #   buildCommand: ""
  #   startCommand: 'nginx -g "daemon off;"' # or your frontend start command
  #   dockerfilePath: client/Dockerfile # Path to your frontend Dockerfile
  #   dockerBuildContext: ./ # Context is the root directory
  #   port: 80
  #   regions:
  #     - oregon # Choose the appropriate region

    - type: web
    name: inv-frontend
    env: docker
    plan: free # or other plans as needed
    buildCommand: |
      docker build --build-arg VUE_APP_BASE_URL=https://inv-w4uc.onrender.com/ -t inv-frontend .
    startCommand: 'nginx -g "daemon off;"'  # Start Nginx to serve the frontend
    dockerfilePath: client/Dockerfile  # Path to your frontend Dockerfile
    dockerBuildContext: ./  # Context is the root directory
    port: 80  # Port for the frontend service
    regions:
      - oregon  # Choose the appropriate region for your frontend